import type { WebsiteTheme } from "@/lib/themes/types";
import type { CssVariableMap } from "@/lib/project-generator/style-engine";

export function mergeWebsiteThemeIntoCssVariables(
  base: CssVariableMap,
  theme?: WebsiteTheme,
): CssVariableMap {
  if (!theme) {
    return base;
  }

  const { colors, typography, layout, radius, shadows, motion } = theme;

  return {
    ...base,
    "--color-background": colors.background,
    "--color-surface": colors.surface,
    "--color-surface-elevated": colors.surfaceElevated,
    "--color-text": colors.text,
    "--color-text-primary": colors.text,
    "--color-text-muted": colors.textMuted,
    "--color-muted": colors.textMuted,
    "--color-primary": colors.primary,
    "--color-primary-hover": colors.primaryHover,
    "--color-secondary": colors.secondary,
    "--color-border": colors.border,
    "--font-heading": typography.headingFont,
    "--font-body": typography.bodyFont,
    "--font-weight-heading": String(typography.headingWeight),
    "--font-weight-body": String(typography.bodyWeight),
    "--letter-spacing-heading": typography.headingLetterSpacing,
    "--layout-max-width": layout.maxWidth,
    "--layout-section-spacing": layout.sectionSpacing,
    "--layout-content-padding": layout.contentPadding,
    "--layout-navigation-height": layout.navigationHeight,
    "--radius-sm": radius.small,
    "--radius-md": radius.medium,
    "--radius-lg": radius.large,
    "--radius-pill": radius.pill,
    "--shadow-sm": shadows.small,
    "--shadow-md": shadows.medium,
    "--shadow-lg": shadows.large,
    "--motion-fast": motion.fast,
    "--motion-normal": motion.normal,
    "--motion-slow": motion.slow,
    "--motion-easing": motion.easing,
    "--container-desktop": layout.maxWidth,
  };
}

export function buildPremiumHeroStylesheet(include: boolean): string {
  if (!include) {
    return "";
  }

  return [
    "",
    "/* Premium restaurant hero — uses WebsiteTheme CSS variables with safe fallbacks */",
    "section.hero-premium {",
    "  min-height: 90vh;",
    "  background: var(--color-background, #090909);",
    "  color: var(--color-text, #fff8ea);",
    "  padding-top: 0;",
    "  padding-bottom: var(--layout-section-spacing, var(--spacing-xl, 3rem));",
    "}",
    ".hero-premium__inner {",
    "  width: 100%;",
    "  max-width: var(--layout-max-width, var(--container-desktop, 72rem));",
    "  margin-inline: auto;",
    "  padding: var(--layout-content-padding, var(--spacing-md, 1rem));",
    "  display: grid;",
    "  gap: var(--spacing-xl, 2rem);",
    "  align-items: center;",
    "}",
    "@media (min-width: 768px) {",
    "  .hero-premium__inner {",
    "    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);",
    "    min-height: calc(90vh - var(--layout-navigation-height, 4.5rem));",
    "  }",
    "}",
    ".hero-premium__tagline {",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "  letter-spacing: var(--letter-spacing-heading, -0.02em);",
    "  text-transform: uppercase;",
    "  color: var(--color-secondary, #d6a84b);",
    "  margin: 0;",
    "}",
    ".hero-premium__title {",
    "  font-family: var(--font-heading, ui-sans-serif, system-ui, sans-serif);",
    "  font-weight: var(--font-weight-heading, 600);",
    "  letter-spacing: var(--letter-spacing-heading, -0.02em);",
    "  font-size: clamp(2rem, 5vw, 3.25rem);",
    "  line-height: var(--line-height-tight, 1.15);",
    "  margin: 0;",
    "  color: var(--color-text, #fff8ea);",
    "}",
    ".hero-premium__description {",
    "  font-family: var(--font-body, ui-sans-serif, system-ui, sans-serif);",
    "  font-weight: var(--font-weight-body, 400);",
    "  font-size: var(--font-size-lg, 1.125rem);",
    "  line-height: var(--line-height-relaxed, 1.65);",
    "  color: var(--color-text-muted, #b8b1a5);",
    "  margin: 0;",
    "  max-width: 36rem;",
    "}",
    ".hero-premium__meta {",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: var(--spacing-sm, 0.5rem);",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "  color: var(--color-text-muted, #b8b1a5);",
    "}",
    ".hero-premium__meta a {",
    "  color: var(--color-text, #fff8ea);",
    "  text-decoration: underline;",
    "  text-underline-offset: 0.15em;",
    "}",
    ".hero-premium__meta a:focus-visible {",
    "  outline: 2px solid var(--color-primary, #d71920);",
    "  outline-offset: 2px;",
    "}",
    ".hero-premium__actions {",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: var(--spacing-sm, 0.75rem);",
    "  width: 100%;",
    "  max-width: 24rem;",
    "}",
    "@media (min-width: 480px) {",
    "  .hero-premium__actions {",
    "    flex-direction: row;",
    "    flex-wrap: wrap;",
    "    align-items: center;",
    "  }",
    "}",
    ".hero-premium__cta-primary {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-height: 2.75rem;",
    "  padding: 0.625rem 1.25rem;",
    "  border-radius: var(--radius-md, 0.625rem);",
    "  background: var(--color-primary, #d71920);",
    "  color: var(--color-text, #fff8ea);",
    "  font-weight: var(--font-weight-heading, 600);",
    "  text-decoration: none;",
    "  transition: background-color var(--motion-fast, 150ms) var(--motion-easing, ease);",
    "}",
    ".hero-premium__cta-primary:hover {",
    "  background: var(--color-primary-hover, #f02a30);",
    "}",
    ".hero-premium__cta-primary:focus-visible {",
    "  outline: 2px solid var(--color-secondary, #d6a84b);",
    "  outline-offset: 2px;",
    "}",
    ".hero-premium__cta-secondary {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-height: 2.75rem;",
    "  padding: 0.625rem 1.25rem;",
    "  border-radius: var(--radius-md, 0.625rem);",
    "  border: 1px solid var(--color-border, rgba(214, 168, 75, 0.24));",
    "  color: var(--color-text, #fff8ea);",
    "  background: transparent;",
    "  text-decoration: none;",
    "  transition: border-color var(--motion-fast, 150ms) var(--motion-easing, ease);",
    "}",
    ".hero-premium__cta-secondary:hover {",
    "  border-color: var(--color-secondary, #d6a84b);",
    "}",
    ".hero-premium__cta-secondary:focus-visible {",
    "  outline: 2px solid var(--color-primary, #d71920);",
    "  outline-offset: 2px;",
    "}",
    ".hero-premium__media {",
    "  width: 100%;",
    "  border-radius: var(--radius-lg, 1rem);",
    "  overflow: hidden;",
    "  background: var(--color-surface-elevated, #191919);",
    "  box-shadow: var(--shadow-md, 0 6px 20px rgba(0, 0, 0, 0.4));",
    "  aspect-ratio: 4 / 5;",
    "}",
    "@media (min-width: 768px) {",
    "  .hero-premium__media {",
    "    aspect-ratio: 3 / 4;",
    "  }",
    "}",
    ".hero-premium__image {",
    "  width: 100%;",
    "  height: 100%;",
    "  object-fit: cover;",
    "  object-position: center 42%;",
    "  display: block;",
    "}",
    "@media (min-width: 768px) {",
    "  .hero-premium__image {",
    "    object-position: 72% center;",
    "  }",
    "}",
    "@media (max-width: 767px) {",
    "  .hero-premium__image {",
    "    object-position: center 38%;",
    "  }",
    "}",
    "@keyframes hero-premium-fade-up {",
    "  from {",
    "    opacity: 0;",
    "    transform: translateY(12px);",
    "  }",
    "  to {",
    "    opacity: 1;",
    "    transform: translateY(0);",
    "  }",
    "}",
    ".hero-premium__animate {",
    "  animation: hero-premium-fade-up var(--motion-normal, 250ms) var(--motion-easing, ease) both;",
    "}",
    ".hero-premium__animate--delay {",
    "  animation-delay: var(--motion-fast, 150ms);",
    "}",
    ".hero-premium__actions.hero-premium__animate {",
    "  animation-delay: calc(var(--motion-fast, 150ms) * 2);",
    "}",
    "@media (prefers-reduced-motion: reduce) {",
    "  .hero-premium__animate {",
    "    animation: none;",
    "    opacity: 1;",
    "    transform: none;",
    "  }",
    "}",
    "",
  ].join("\n");
}

export function buildPremiumLandingSectionStyles(include: boolean): string {
  if (!include) {
    return "";
  }

  return [
    "",
    ".landing-section-lead {",
    "  margin: 0;",
    "  max-width: 42rem;",
    "  color: var(--color-text-muted, #b8b1a5);",
    "  font-size: var(--font-size-lg, 1.125rem);",
    "  line-height: var(--line-height-relaxed, 1.65);",
    "}",
    ".landing-menu-section,",
    ".landing-business-section {",
    "  background: var(--color-background, #090909);",
    "  color: var(--color-text, #fff8ea);",
    "  padding-block: var(--layout-section-spacing, 3rem);",
    "}",
    ".landing-menu-figure {",
    "  margin: 0;",
    "  width: 100%;",
    "  max-width: 100%;",
    "  overflow: hidden;",
    "  border-radius: var(--radius-lg, 1rem);",
    "  border: 1px solid var(--color-border, rgba(214, 168, 75, 0.24));",
    "  background: var(--color-surface-elevated, #191919);",
    "}",
    ".landing-menu-image {",
    "  display: block;",
    "  width: 100%;",
    "  height: auto;",
    "  max-width: 100%;",
    "  object-fit: contain;",
    "}",
    ".landing-menu-actions {",
    "  margin: 0;",
    "}",
    ".landing-link-button {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-height: 2.75rem;",
    "  padding: 0.625rem 1rem;",
    "  border-radius: var(--radius-md, 0.625rem);",
    "  border: 1px solid var(--color-border, rgba(214, 168, 75, 0.24));",
    "  color: var(--color-text, #fff8ea);",
    "  text-decoration: none;",
    "}",
    ".landing-link-button:focus-visible {",
    "  outline: 2px solid var(--color-primary, #d71920);",
    "  outline-offset: 2px;",
    "}",
    ".landing-business-grid {",
    "  display: grid;",
    "  gap: var(--spacing-xl, 2rem);",
    "}",
    "@media (min-width: 768px) {",
    "  .landing-business-grid {",
    "    grid-template-columns: minmax(0, 1fr) minmax(0, 1.1fr);",
    "    align-items: start;",
    "  }",
    "}",
    ".landing-business-details {",
    "  margin: 0;",
    "  display: grid;",
    "  gap: var(--spacing-md, 1rem);",
    "}",
    ".landing-business-row {",
    "  display: grid;",
    "  gap: 0.35rem;",
    "}",
    ".landing-business-row dt {",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "  letter-spacing: 0.04em;",
    "  text-transform: uppercase;",
    "  color: var(--color-secondary, #d6a84b);",
    "}",
    ".landing-business-row dd {",
    "  margin: 0;",
    "  color: var(--color-text, #fff8ea);",
    "}",
    ".landing-business-link {",
    "  color: inherit;",
    "  text-decoration: underline;",
    "  text-underline-offset: 0.15em;",
    "  overflow-wrap: anywhere;",
    "}",
    ".landing-business-link:focus-visible {",
    "  outline: 2px solid var(--color-primary, #d71920);",
    "  outline-offset: 2px;",
    "}",
    ".landing-hours-list {",
    "  list-style: none;",
    "  margin: 0;",
    "  padding: 0;",
    "  display: grid;",
    "  gap: 0.35rem;",
    "}",
    ".landing-hours-list li {",
    "  display: flex;",
    "  justify-content: space-between;",
    "  gap: 1rem;",
    "  flex-wrap: wrap;",
    "}",
    ".landing-hours-note {",
    "  margin: 0.75rem 0 0;",
    "  color: var(--color-text-muted, #b8b1a5);",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "}",
    ".pg-page {",
    "  overflow-x: clip;",
    "  max-width: 100%;",
    "}",
    ".pg-legal-page {",
    "  max-width: var(--container-desktop, 72rem);",
    "  margin: 0 auto;",
    "  padding: var(--spacing-xl, 2rem) var(--spacing-md, 1rem);",
    "  display: grid;",
    "  gap: var(--spacing-md, 1rem);",
    "}",
    ".pg-legal-page__actions {",
    "  margin-top: var(--spacing-md, 1rem);",
    "}",
    ".site-footer-business__grid {",
    "  display: grid;",
    "  gap: var(--spacing-lg, 1.5rem);",
    "}",
    "@media (min-width: 768px) {",
    "  .site-footer-business__grid {",
    "    grid-template-columns: repeat(2, minmax(0, 1fr));",
    "  }",
    "}",
    "@media (min-width: 1024px) {",
    "  .site-footer-business__grid {",
    "    grid-template-columns: repeat(4, minmax(0, 1fr));",
    "  }",
    "}",
    ".site-footer-business__name {",
    "  margin: 0;",
    "  font-size: var(--font-size-lg, 1.125rem);",
    "  font-weight: var(--font-weight-semibold, 600);",
    "}",
    ".site-footer-business__tagline {",
    "  margin: 0.35rem 0 0;",
    "  color: var(--color-text-muted, #b8b1a5);",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "}",
    ".site-footer-business__heading {",
    "  margin: 0 0 0.75rem;",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "  font-weight: var(--font-weight-semibold, 600);",
    "  letter-spacing: 0.04em;",
    "  text-transform: uppercase;",
    "}",
    ".site-footer-business__list,",
    ".site-footer-business__hours {",
    "  list-style: none;",
    "  margin: 0;",
    "  padding: 0;",
    "  display: grid;",
    "  gap: 0.5rem;",
    "}",
    ".site-footer-business__hours li {",
    "  display: flex;",
    "  justify-content: space-between;",
    "  gap: 0.75rem;",
    "  flex-wrap: wrap;",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "}",
    ".site-footer-business__link {",
    "  color: inherit;",
    "  text-decoration: underline;",
    "  text-underline-offset: 0.15em;",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "  overflow-wrap: anywhere;",
    "}",
    ".site-footer-business__link:focus-visible {",
    "  outline: 2px solid var(--color-primary, #d71920);",
    "  outline-offset: 2px;",
    "}",
    ".site-footer-business__bottom {",
    "  border-top-width: 1px;",
    "  padding-top: var(--spacing-md, 1rem);",
    "}",
    ".site-footer-business__bottom-inner {",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: var(--spacing-md, 1rem);",
    "}",
    "@media (min-width: 768px) {",
    "  .site-footer-business__bottom-inner {",
    "    flex-direction: row;",
    "    flex-wrap: wrap;",
    "    align-items: center;",
    "    justify-content: space-between;",
    "  }",
    "}",
    ".site-footer-business__copyright {",
    "  margin: 0;",
    "  font-size: var(--font-size-sm, 0.875rem);",
    "  color: var(--color-text-muted, #b8b1a5);",
    "}",
    ".site-footer-business__legal,",
    ".site-footer-business__social {",
    "  display: flex;",
    "  flex-wrap: wrap;",
    "  gap: var(--spacing-sm, 0.75rem);",
    "}",
    "",
  ].join("\n");
}
