import type { CompiledPage } from "@/lib/website-compiler/types";
import type { BusinessIndustryProfile } from "@/lib/industries/business/types";
import { BUSINESS_SECTION_ANCHORS } from "@/lib/industries/business/landing";
import type { PageSectionConfig } from "@/lib/project-generator/react-utils";

function emptySectionFields(): Pick<
  PageSectionConfig,
  | "missingData"
  | "contentBlocks"
  | "media"
  | "ctaReferences"
  | "mediaReferences"
  | "menuItems"
  | "faqItems"
  | "trustBadges"
  | "isPlaceholder"
> {
  return {
    missingData: [],
    contentBlocks: [],
    media: [],
    ctaReferences: [],
    mediaReferences: [],
    menuItems: [],
    faqItems: [],
    trustBadges: [],
    isPlaceholder: false,
  };
}

export function buildBusinessHomeSections(
  page: CompiledPage,
  profile: BusinessIndustryProfile,
): PageSectionConfig[] {
  const base = emptySectionFields();

  return [
    {
      ...base,
      id: "home",
      title: profile.companyName,
      name: "HeroSection",
      eyebrow: profile.tagline,
      description: profile.description,
      type: "hero",
      order: 1,
      priority: 100,
      hierarchyLevel: "dominant",
      visualWeight: "very-high",
      purpose: page.pageObjective,
      componentName: "HeroSection",
      primaryCTA: profile.primaryCta,
      secondaryCTA: "Leistungen ansehen",
      headingLevel: 1,
      sourcePatternIds: ["hero"],
      contentBody: profile.description,
      contentLines: [profile.tagline],
      primaryCtaHref: profile.email ? `mailto:${profile.email}` : `#${BUSINESS_SECTION_ANCHORS.contact}`,
      secondaryCtaHref: `#${BUSINESS_SECTION_ANCHORS.services}`,
      ctaReferences: [
        profile.email ? `mailto:${profile.email}` : `#${BUSINESS_SECTION_ANCHORS.contact}`,
        `#${BUSINESS_SECTION_ANCHORS.services}`,
      ],
      heroLayout: "legacy",
      tagline: profile.tagline,
      phone: profile.phone,
      address: profile.address,
    },
    {
      ...base,
      id: BUSINESS_SECTION_ANCHORS.about,
      title: "Über uns",
      name: "ContentSection",
      eyebrow: profile.companyName,
      description: profile.description,
      type: "content",
      order: 2,
      priority: 80,
      hierarchyLevel: "primary",
      visualWeight: "high",
      purpose: "Introduce the company",
      componentName: "ContentSection",
      primaryCTA: null,
      secondaryCTA: null,
      headingLevel: 2,
      sourcePatternIds: ["feature-grid"],
      contentBody: profile.description,
      contentBlocks: profile.description
        .split(". ")
        .filter(Boolean)
        .map((part) => (part.endsWith(".") ? part : `${part}.`)),
      contentLines: profile.description.split(". ").filter(Boolean),
    },
    {
      ...base,
      id: BUSINESS_SECTION_ANCHORS.services,
      title: "Leistungen",
      name: "FeatureGridSection",
      eyebrow: "Services",
      description: "Unsere Leistungen im Überblick",
      type: "feature-grid",
      order: 3,
      priority: 85,
      hierarchyLevel: "primary",
      visualWeight: "high",
      purpose: "Present service offerings",
      componentName: "FeatureGridSection",
      primaryCTA: profile.primaryCta,
      secondaryCTA: null,
      headingLevel: 2,
      sourcePatternIds: ["feature-grid"],
      contentBody: profile.services.map((item) => item.title).join(" | "),
      contentBlocks: profile.services.map((item) => `${item.title}: ${item.description}`),
      contentLines: profile.services.map((item) => item.title),
    },
    {
      ...base,
      id: BUSINESS_SECTION_ANCHORS.benefits,
      title: "Ihre Vorteile",
      name: "FeatureGridSection",
      eyebrow: "Benefits",
      description: "Warum Kunden uns wählen",
      type: "feature-grid",
      order: 4,
      priority: 75,
      hierarchyLevel: "secondary",
      visualWeight: "medium",
      purpose: "Highlight benefits",
      componentName: "FeatureGridSection",
      primaryCTA: null,
      secondaryCTA: null,
      headingLevel: 2,
      sourcePatternIds: ["feature-grid"],
      contentBody: profile.benefits.map((item) => item.title).join(" | "),
      contentBlocks: profile.benefits.map((item) => `${item.title}: ${item.description}`),
      contentLines: profile.benefits.map((item) => item.title),
    },
    {
      ...base,
      id: BUSINESS_SECTION_ANCHORS.testimonials,
      title: "Kundenstimmen",
      name: "TestimonialSection",
      eyebrow: "Testimonials",
      description: "Was unsere Kunden sagen",
      type: "testimonials",
      order: 5,
      priority: 70,
      hierarchyLevel: "secondary",
      visualWeight: "medium",
      purpose: "Social proof",
      componentName: "TestimonialSection",
      primaryCTA: null,
      secondaryCTA: null,
      headingLevel: 2,
      sourcePatternIds: ["testimonials"],
      contentBody: profile.testimonials.map((item) => item.quote).join(" | "),
      contentBlocks: profile.testimonials.map(
        (item) => `${item.quote} — ${item.author}, ${item.role}`,
      ),
      contentLines: profile.testimonials.map((item) => item.quote),
    },
    {
      ...base,
      id: BUSINESS_SECTION_ANCHORS.faq,
      title: "Häufige Fragen",
      name: "FAQSection",
      eyebrow: "FAQ",
      description: "Antworten auf häufige Fragen",
      type: "faq",
      order: 6,
      priority: 65,
      hierarchyLevel: "secondary",
      visualWeight: "medium",
      purpose: "Answer common questions",
      componentName: "FAQSection",
      primaryCTA: null,
      secondaryCTA: null,
      headingLevel: 2,
      sourcePatternIds: ["faq"],
      contentBody: profile.faq.map((item) => item.question).join(" | "),
      faqItems: profile.faq.map((item) => ({
        id: item.id,
        question: item.question,
        answer: item.answer,
      })),
      contentLines: profile.faq.map((item) => item.question),
    },
    {
      ...base,
      id: BUSINESS_SECTION_ANCHORS.contact,
      title: "Kontakt",
      name: "ContactSection",
      eyebrow: "Kontakt",
      description: profile.address,
      type: "contact",
      order: 7,
      priority: 90,
      hierarchyLevel: "primary",
      visualWeight: "high",
      purpose: "Enable contact",
      componentName: "ContactSection",
      primaryCTA: profile.primaryCta,
      secondaryCTA: profile.phone,
      headingLevel: 2,
      sourcePatternIds: ["feature-grid"],
      contentBody: `${profile.address} | ${profile.phone} | ${profile.email}`,
      contentLines: [profile.address, profile.phone, profile.email],
      phone: profile.phone,
      address: profile.address,
      primaryCtaHref: profile.email ? `mailto:${profile.email}` : `#${BUSINESS_SECTION_ANCHORS.contact}`,
    },
  ];
}
