import type { CompiledWebsiteProject } from "@/lib/website-compiler/types";
import { businessProfileForComponentExport } from "@/lib/industries/restaurant/landing";
import { businessProfileToFooterProfile } from "@/lib/industries/business/footer-adapter";
import {
  generatePremiumSectionWrapper,
  headerComment,
  premiumSectionImports,
  STYLE_IMPORT,
} from "@/lib/project-generator/visual-component-utils";
import { isClientComponent } from "@/lib/project-generator/react-component-utils";

function requireBusinessProfile(project: CompiledWebsiteProject) {
  if (!project.businessProfile) {
    throw new Error("Business section generators require businessProfile on the compiled project");
  }
  return project.businessProfile;
}

export function generateBusinessContentSectionSource(): string {
  return generatePremiumSectionWrapper("ContentSection", [
    "          {(() => {",
    "            const paragraphs =",
    "              section.contentBlocks.length > 0 ? section.contentBlocks : (section.contentLines ?? []);",
    "            if (paragraphs.length === 0) {",
    '              return section.description ? (',
    '                <p className="max-w-3xl text-[length:var(--font-size-md)] leading-relaxed text-[var(--color-text-muted)]">',
    "                  {section.description}",
    "                </p>",
    "              ) : null;",
    "            }",
    "            return (",
    '              <Stack gap="md" className="max-w-3xl">',
    "                {paragraphs.map((block) => (",
    '                  <p key={block} className="text-[length:var(--font-size-md)] leading-relaxed text-[var(--color-text-muted)]">',
    "                    {block}",
    "                  </p>",
    "                ))}",
    "              </Stack>",
    "            );",
    "          })()}",
    "          {section.primaryCTA && section.primaryCtaHref ? (",
    "            <ButtonLink cta={{ label: section.primaryCTA, href: section.primaryCtaHref, variant: 'primary' }} />",
    "          ) : null}",
  ], ["import { ButtonLink } from './ButtonLink';"]);
}

export function generateBusinessFeatureGridSectionSource(): string {
  return generatePremiumSectionWrapper("FeatureGridSection", [
    "          {(() => {",
    "            const items = section.contentBlocks.length > 0 ? section.contentBlocks : (section.contentLines ?? []);",
    "            if (items.length === 0) {",
    "              return null;",
    "            }",
    "            return (",
    '              <ResponsiveGrid columns={3}>',
    "                {items.map((item) => {",
    "                  const splitAt = item.indexOf(': ');",
    "                  const title = splitAt > 0 ? item.slice(0, splitAt) : item;",
    "                  const description = splitAt > 0 ? item.slice(splitAt + 2) : '';",
    "                  const initial = title.trim().charAt(0).toUpperCase() || '?';",
    "                  return (",
    '                    <li key={item}>',
    '                      <Card variant="interactive" as="article">',
    '                        <Stack gap="sm">',
    '                          <span',
    '                            aria-hidden="true"',
    '                            className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--color-primary)]/10 text-sm font-[var(--font-weight-semibold)] text-[var(--color-primary)]"',
    "                          >",
    "                            {initial}",
    "                          </span>",
    '                          <h3 className="text-base font-[var(--font-weight-medium)]">{title}</h3>',
    "                          {description ? (",
    '                            <p className="text-[length:var(--font-size-sm)] text-[var(--color-text-muted)]">',
    "                              {description}",
    "                            </p>",
    "                          ) : null}",
    "                        </Stack>",
    "                      </Card>",
    "                    </li>",
    "                  );",
    "                })}",
    "              </ResponsiveGrid>",
    "            );",
    "          })()}",
  ], ["import { Card } from './Card';", "import { ResponsiveGrid } from './ResponsiveGrid';"]);
}

export function generateBusinessTestimonialSectionSource(): string {
  return generatePremiumSectionWrapper("TestimonialSection", [
    "          {(() => {",
    "            const items = section.contentBlocks.length > 0 ? section.contentBlocks : (section.contentLines ?? []);",
    "            if (items.length === 0) {",
    "              return null;",
    "            }",
    "            return (",
    '              <ResponsiveGrid columns={2}>',
    "                {items.map((block) => {",
    "                  const separator = block.lastIndexOf(' — ');",
    "                  const quote = separator > 0 ? block.slice(0, separator) : block;",
    "                  const attribution = separator > 0 ? block.slice(separator + 3) : '';",
    "                  const comma = attribution.indexOf(', ');",
    "                  const author = comma > 0 ? attribution.slice(0, comma) : attribution;",
    "                  const role = comma > 0 ? attribution.slice(comma + 2) : '';",
    "                  return (",
    '                    <li key={block}>',
    '                      <Card variant="testimonial" className="flex h-full flex-col gap-[var(--spacing-md)]">',
    '                        <p className="text-[length:var(--font-size-md)] leading-relaxed text-[var(--color-text-muted)]">',
    '                          {`„${quote}"`}',
    "                        </p>",
    "                        {(author || role) ? (",
    '                          <footer className="mt-auto text-[length:var(--font-size-sm)]">',
    "                            {author ? (",
    '                              <p className="font-[var(--font-weight-medium)] text-[var(--color-text)]">{author}</p>',
    "                            ) : null}",
    "                            {role ? (",
    '                              <p className="text-[var(--color-text-muted)]">{role}</p>',
    "                            ) : null}",
    "                          </footer>",
    "                        ) : null}",
    "                      </Card>",
    "                    </li>",
    "                  );",
    "                })}",
    "              </ResponsiveGrid>",
    "            );",
    "          })()}",
  ], ["import { Card } from './Card';", "import { ResponsiveGrid } from './ResponsiveGrid';"]);
}

export function generateBusinessContactSectionSource(project: CompiledWebsiteProject): string {
  requireBusinessProfile(project);
  const profile = businessProfileToFooterProfile(project.businessProfile!);
  const profileLiteral = JSON.stringify(businessProfileForComponentExport(profile), null, 2);
  return [
    headerComment("ContactSection"),
    ...premiumSectionImports([
      "import { ButtonLink } from './ButtonLink';",
      "import { ContactForm } from './ContactForm';",
    ]),
    "",
    `const businessProfile = ${profileLiteral};`,
    "",
    "export function ContactSection({ section }: SectionComponentProps) {",
    "  const telHref = businessProfile.phoneTelHref;",
    "  const mapsQuery = encodeURIComponent(businessProfile.address);",
    "  const primaryHref = section.primaryCtaHref ?? businessProfile.emailMailtoHref ?? '/#contact';",
    "",
    "  return (",
    "    <SectionShell id={section.id} headingId={`${section.id}-heading`} className=\"landing-business-section\">",
    "      <Container>",
    '        <div className="grid gap-[var(--spacing-lg)] md:grid-cols-2 md:items-start">',
    '          <Stack gap="md">',
    "            <SectionHeading section={section} />",
    "            {section.description ? (",
    '              <p className="landing-section-lead">{section.description}</p>',
    "            ) : null}",
    '            <dl className="landing-business-details">',
    '              <div className="landing-business-row">',
    '                <dt>Adresse</dt>',
    "                <dd>",
    "                  <a",
    '                    className="landing-business-link"',
    "                    href={`https://www.google.com/maps/search/?api=1&query=${mapsQuery}`}",
    "                    target=\"_blank\"",
    "                    rel=\"noopener noreferrer\"",
    "                  >",
    "                    {businessProfile.addressLines.map((line) => (",
    '                      <span key={line} className="block">',
    "                        {line}",
    "                      </span>",
    "                    ))}",
    "                  </a>",
    "                </dd>",
    "              </div>",
    '              <div className="landing-business-row">',
    '                <dt>Telefon</dt>',
    "                <dd>",
    '                  <a className="landing-business-link" href={telHref}>',
    "                    {businessProfile.phone}",
    "                  </a>",
    "                </dd>",
    "              </div>",
    "              {businessProfile.email && businessProfile.emailMailtoHref ? (",
    '                <div className="landing-business-row">',
    '                  <dt>E-Mail</dt>',
    "                  <dd>",
    '                    <a className="landing-business-link" href={businessProfile.emailMailtoHref}>',
    "                      {businessProfile.email}",
    "                    </a>",
    "                  </dd>",
    "                </div>",
    "              ) : null}",
    '              <div className="landing-business-row">',
    '                <dt>Öffnungszeiten</dt>',
    "                <dd>",
    '                  <ul className="landing-hours-list">',
    "                    {businessProfile.openingHours.map((entry) => (",
    '                      <li key={`${entry.days}-${entry.hours}`}>',
    "                        <span>{entry.days}</span>",
    "                        <span>{entry.hours}</span>",
    "                      </li>",
    "                    ))}",
    "                  </ul>",
    "                </dd>",
    "              </div>",
    "            </dl>",
    "            {section.primaryCTA ? (",
    `              <ButtonLink cta={{ label: section.primaryCTA, href: primaryHref, variant: 'primary' }} />`,
    "            ) : null}",
    "          </Stack>",
    "          <ContactForm />",
    "        </div>",
    "      </Container>",
    "    </SectionShell>",
    "  );",
    "}",
    "",
  ].join("\n");
}

export function generateBusinessContactFormSource(): string {
  const clientDirective = isClientComponent("ContactForm") ? "'use client';\n\n" : "";

  return [
    headerComment("ContactForm"),
    clientDirective,
    STYLE_IMPORT,
    "import Link from 'next/link';",
    "import { useState } from 'react';",
    "",
    "type FormStatus = 'idle' | 'loading' | 'success' | 'error';",
    "",
    "type ContactFormProps = {",
    "  className?: string;",
    "};",
    "",
    "export function ContactForm({ className }: ContactFormProps) {",
    "  const [status, setStatus] = useState<FormStatus>('idle');",
    "",
    "  return (",
    "    <form",
    "      className={cn('space-y-[var(--spacing-md)]', className)}",
    "      noValidate",
    '      aria-label="Kontaktformular"',
    "      onSubmit={(event) => {",
    "        event.preventDefault();",
    "        setStatus('loading');",
    "        window.setTimeout(() => setStatus('success'), 600);",
    "      }}",
    "    >",
    "      <div>",
    '        <label htmlFor="name" className="block text-sm font-[var(--font-weight-medium)]">Name *</label>',
    '        <input id="name" name="name" type="text" placeholder="Max Mustermann" className={variants.input} required disabled={status === \'loading\'} />',
    "      </div>",
    "      <div>",
    '        <label htmlFor="email" className="block text-sm font-[var(--font-weight-medium)]">E-Mail *</label>',
    '        <input id="email" name="email" type="email" placeholder="ihre@email.de" className={variants.input} required disabled={status === \'loading\'} />',
    "      </div>",
    "      <div>",
    '        <label htmlFor="message" className="block text-sm font-[var(--font-weight-medium)]">Nachricht *</label>',
    '        <textarea id="message" name="message" placeholder="Wie können wir helfen?" className={variants.input} rows={4} required disabled={status === \'loading\'} />',
    "      </div>",
    '      <label className="flex items-start gap-[var(--spacing-sm)] text-sm">',
    '        <input type="checkbox" required disabled={status === \'loading\'} />',
    "        <span>",
    "          Ich willige in die Verarbeitung meiner Angaben zur Bearbeitung der Anfrage ein. Details in der{\" \"}",
    '          <Link href="/datenschutz" className="underline underline-offset-2">',
    "            Datenschutzerklärung",
    "          </Link>",
    "          .",
    "        </span>",
    "      </label>",
    "      {status === 'success' ? (",
    '        <p className="text-sm text-[var(--color-primary)]" role="status">',
    "          Vielen Dank — wir melden uns in der Regel innerhalb eines Werktags.",
    "        </p>",
    "      ) : null}",
    "      <button",
    '        type="submit"',
    "        className={cn(variants.buttonPrimary, variants.motionSafe, 'min-h-11')}",
    "        disabled={status === 'loading'}",
    "        aria-busy={status === 'loading'}",
    "      >",
    "        {status === 'loading' ? 'Wird gesendet …' : 'Anfrage senden'}",
    "      </button>",
    "    </form>",
    "  );",
    "}",
    "",
  ].join("\n");
}
