/**
 * GENERATED CSS VARIABLE MAP — Sprint 8.2D
 */

export const cssVariables = {
  "--color-primary": "#D71920",
  "--color-secondary": "#D6A84B",
  "--color-accent": "#F59E0B",
  "--color-background": "#090909",
  "--color-surface": "#121212",
  "--color-text": "#FFF8EA",
  "--color-text-primary": "#FFF8EA",
  "--color-muted": "#B8B1A5",
  "--color-text-muted": "#B8B1A5",
  "--color-border": "rgba(214, 168, 75, 0.24)",
  "--color-error": "#DC2626",
  "--font-heading": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  "--font-body": "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  "--font-size-xs": "0.75rem",
  "--font-size-sm": "0.875rem",
  "--font-size-md": "1rem",
  "--font-size-lg": "1.125rem",
  "--font-size-xl": "1.25rem",
  "--font-size-2xl": "clamp(1.5rem, 2.5vw, 2rem)",
  "--font-size-display": "clamp(2.25rem, 4vw, 3rem)",
  "--font-weight-regular": "400",
  "--font-weight-medium": "500",
  "--font-weight-semibold": "600",
  "--font-weight-bold": "700",
  "--line-height-tight": "1.2",
  "--line-height-snug": "1.35",
  "--line-height-normal": "1.5",
  "--line-height-relaxed": "1.65",
  "--spacing-xs": "0.75rem",
  "--spacing-sm": "1rem",
  "--spacing-md": "1.5rem",
  "--spacing-lg": "5rem",
  "--spacing-xl": "4rem",
  "--spacing-2xl": "6rem",
  "--radius-sm": "0.375rem",
  "--radius-md": "0.625rem",
  "--radius-lg": "1rem",
  "--radius-pill": "9999px",
  "--shadow-sm": "0 1px 2px rgba(0, 0, 0, 0.45)",
  "--shadow-md": "0 6px 20px rgba(0, 0, 0, 0.4)",
  "--shadow-lg": "0 16px 40px rgba(0, 0, 0, 0.45)",
  "--shadow-xl": "0 20px 40px rgba(0,0,0,0.14)",
  "--container-mobile": "100%",
  "--container-tablet": "65ch",
  "--container-desktop": "72rem",
  "--breakpoint-mobile": "640px",
  "--breakpoint-tablet": "768px",
  "--breakpoint-desktop": "1024px",
  "--z-index-header": "40",
  "--z-index-sticky": "30",
  "--z-index-modal": "50",
  "--dark-color-background": "#0B0B0B",
  "--dark-color-surface": "#141414",
  "--dark-color-text": "#F5F5F5",
  "--dark-color-muted": "#A3A3A3",
  "--color-surface-elevated": "#191919",
  "--color-primary-hover": "#F02A30",
  "--font-weight-heading": "600",
  "--font-weight-body": "400",
  "--letter-spacing-heading": "-0.02em",
  "--layout-max-width": "72rem",
  "--layout-section-spacing": "5rem",
  "--layout-content-padding": "1.5rem",
  "--layout-navigation-height": "4.5rem",
  "--motion-fast": "150ms",
  "--motion-normal": "250ms",
  "--motion-slow": "400ms",
  "--motion-easing": "cubic-bezier(0.4, 0, 0.2, 1)",
} as const;

export type CssVariables = typeof cssVariables;

export function cssVariableBlock(selector = ':root'): string {
  const lines = Object.entries(cssVariables).map(
    ([name, value]) => `  ${name}: ${value};`,
  );
  return `${selector} {\n${lines.join('\n')}\n}`;
}
