import type { PageDnaContext, PageRole } from "@/lib/website-blueprint-page-dna";
import { getComponentTreeNodes, getPageSections } from "@/lib/website-blueprint-page-dna";

type ComponentDnaFields = {
  purpose: string;
  content: string;
  hierarchy: string;
  responsive: string;
  spacing: string;
  typography: string;
  accessibility: string;
  seoRelevance: string;
  interactionStates: string;
  animation: string;
  variants: string;
  placeholders: string;
  devNotes: string;
};

function normalizeComponentName(name: string): string {
  if (name.startsWith("MenuCategory_")) {
    return "MenuCategorySection";
  }
  if (name.startsWith("Service_")) {
    return "ServiceCard";
  }
  if (name.endsWith("Hero") && name !== "HeroSection") {
    return "PageHero";
  }
  return name;
}

function designTokensRef(): string {
  return "Use Design System DNA tokens (colors, spacing, radius, typography, motion) — no local hex.";
}

function formatComponentDna(name: string, fields: ComponentDnaFields): string {
  return [
    `Component: ${name}`,
    `Purpose: ${fields.purpose}`,
    `Content: ${fields.content}`,
    `Hierarchy: ${fields.hierarchy}`,
    `Responsive: ${fields.responsive}`,
    `Spacing: ${fields.spacing}`,
    `Typography: ${fields.typography}`,
    `Accessibility: ${fields.accessibility}`,
    `SEO: ${fields.seoRelevance}`,
    `Interaction: ${fields.interactionStates}`,
    `Animation: ${fields.animation}`,
    `Variants: ${fields.variants}`,
    `Placeholders: ${fields.placeholders}`,
    `Dev notes: ${fields.devNotes}`,
  ].join(" | ");
}

function hierarchyLine(
  name: string,
  index: number,
  tree: string[],
): string {
  const parent = index > 0 ? tree[index - 1] : "document";
  const child = index < tree.length - 1 ? tree[index + 1] : "none";
  return `Parent: ${parent} → Self: ${name} → Child: ${child}; slot in page layout tree position ${index + 1}/${tree.length}.`;
}

function baseMotion(ctx: PageDnaContext): string {
  return ctx.prefersMotion || ctx.tier === "premium"
    ? "Motion tokens durationNormal + easingEmphasized; respect prefers-reduced-motion."
    : "Motion tokens durationFast; minimal transform; respect prefers-reduced-motion.";
}

function buildComponentFields(
  name: string,
  ctx: PageDnaContext,
  index: number,
  tree: string[],
): ComponentDnaFields {
  const normalized = normalizeComponentName(name);
  const hierarchy = hierarchyLine(name, index, tree);
  const tokens = designTokensRef();
  const business = ctx.brief.business_name;
  const section = getPageSections(ctx).find((entry) =>
    name.startsWith(entry.name.replace(/_/g, "")),
  );

  const templates: Record<string, ComponentDnaFields> = {
    SiteHeader: {
      purpose: "Global navigation, brand mark, and primary CTA access on every page.",
      content: `Logo text „${business}"; nav links to sitemap pages; header CTA „${ctx.primaryCta}".`,
      hierarchy,
      responsive: "Desktop horizontal nav; mobile hamburger + slide-down panel; sticky after 64px scroll.",
      spacing: "Height 64px; px spacing-4 mobile / spacing-8 desktop; nav gap spacing-6.",
      typography: "Logo: label token weight 600; nav links: bodySmall; CTA: button token.",
      accessibility:
        "nav landmark; aria-current on active route; focus trap in mobile menu; skip link before header.",
      seoRelevance: "Internal links to all indexable pages; no H1 in header.",
      interactionStates: "Hover underline nav; mobile toggle aria-expanded; sticky shadowSmall on scroll.",
      animation: "Mobile menu slide-down 250ms; backdrop blur on sticky state.",
      variants: "Default sticky; optional transparent-on-hero variant at top of home only.",
      placeholders: "Social icons [PLACEHOLDER] if not in brief.",
      devNotes: `Single shared component; pass nav items from sitemap; ${tokens}`,
    },
    SiteFooter: {
      purpose: "Sitewide footer navigation, contact snippet, legal links.",
      content: `Nav repeat (${ctx.sitemap.join(", ")}); contact [PLACEHOLDER: phone/email]; legal [PLACEHOLDER: Impressum/Datenschutz].`,
      hierarchy,
      responsive: "Mobile stacked columns; tablet 2 col; desktop 4 col + bottom bar.",
      spacing: "padding-top spacing-16; column gap spacing-8; legal margin-top spacing-8.",
      typography: "Column headings h4; links bodySmall; legal caption.",
      accessibility: "footer landmark; external links marked; sufficient touch targets.",
      seoRelevance: "NAP consistency with location pages; internal links to all pages.",
      interactionStates: "Link hover underline; focus ring on all links.",
      animation: "None.",
      variants: "Standard footer; optional local SEO NAP block when location in brief.",
      placeholders: ctx.brief.location
        ? `Address line: ${ctx.brief.location} [PLACEHOLDER: street/PLZ]`
        : "[PLACEHOLDER: address, phone, email]",
      devNotes: `Shared layout component; ${tokens}`,
    },
    HeroSection: {
      purpose: "Above-the-fold value proposition and primary conversion action.",
      content: `H1 ${business}; subhead from goal „${ctx.brief.website_goal.slice(0, 80)}"; CTAs „${ctx.primaryCta}" / „${ctx.secondaryCta}"; USP eyebrow „${ctx.usp.slice(0, 50)}".`,
      hierarchy,
      responsive: "Mobile single column full-width CTAs; desktop split 50/50 optional; min-height 55–70vh.",
      spacing: "padding-y spacing-16 mobile / spacing-24 desktop; gap spacing-6 between headline and CTAs.",
      typography: "H1 displayL/h1 token; subhead bodyLarge; eyebrow label token.",
      accessibility: "One H1 per page; CTAs min 44px; contrast check hero text over image overlay.",
      seoRelevance: "Contains page H1 and primary keyword intent; LCP image priority.",
      interactionStates: "Button hover/active/focus; optional video play control.",
      animation: `Hero stagger headline→CTA ${ctx.prefersMotion ? "600ms" : "350ms"}; ${baseMotion(ctx)}`,
      variants: "Centered; split media; video background [PLACEHOLDER].",
      placeholders: "Hero image/video [PLACEHOLDER: client asset]; background media alt text required.",
      devNotes: `Export hero content from page module; next/image priority; ${tokens}`,
    },
    PageHero: {
      purpose: "Page-specific hero introducing context before main sections.",
      content: section
        ? section.contentRequirements
        : `Contextual intro for ${ctx.page} supporting ${ctx.brief.website_goal}.`,
      hierarchy,
      responsive: "Compact vs home hero; mobile stack; tablet partial split.",
      spacing: "padding-y spacing-12 mobile / spacing-16 desktop.",
      typography: "H1 h1 token (one per page); subhead bodyLarge.",
      accessibility: "Single H1; readable overlay if background image.",
      seoRelevance: "Page H1 + meta alignment; breadcrumb optional.",
      interactionStates: "Primary/secondary CTA states from button system.",
      animation: "Fade-in headline; reduced motion safe.",
      variants: `Role variant for ${ctx.role}; shared PageHero shell.`,
      placeholders: "Background image [PLACEHOLDER] when role requires visual.",
      devNotes: `Compose from HeroSection with role-specific content props; ${tokens}`,
    },
    TrustBar: {
      purpose: "Immediate credibility strip using brief USP.",
      content: ctx.usp,
      hierarchy,
      responsive: "Mobile 2×2 grid or horizontal scroll; desktop inline row.",
      spacing: "padding-y spacing-6; gap spacing-4 between badges.",
      typography: "label token; max 6 words per badge.",
      accessibility: "ul/li list; icons decorative with text.",
      seoRelevance: "Supports E-E-A-T; no heading level change.",
      interactionStates: "Optional link to About; static badges default.",
      animation: "Stagger fade-in 60ms per badge.",
      variants: "Icon+text badges; text-only.",
      placeholders: "Certification logos only if client supplies.",
      devNotes: `Map USP string to 3–4 badges in content module; ${tokens}`,
    },
    FeaturedItems: {
      purpose: "Highlight top services/menu items from brief.",
      content:
        ctx.services.length > 0
          ? ctx.services.slice(0, 3).join(", ")
          : "[PLACEHOLDER: featured items]",
      hierarchy,
      responsive: "1 col mobile; 2 col tablet; 3 col desktop.",
      spacing: "Section spacing-16/24; card gap spacing-6; card padding spacing-6.",
      typography: "Section h2; item title h4; description bodySmall.",
      accessibility: "Cards as articles; image alt per item name.",
      seoRelevance: "Internal links to menu/services pages.",
      interactionStates: "Card hover lift desktop; entire card clickable.",
      animation: "Scroll reveal stagger.",
      variants: "ItemCard grid; optional price line [PLACEHOLDER].",
      placeholders: "Item descriptions and prices [PLACEHOLDER]; images [PLACEHOLDER].",
      devNotes: `Reuse ProductCard variant from Design System; ${tokens}`,
    },
    USPGrid: {
      purpose: "Expand unique selling proposition into scannable benefits.",
      content: ctx.usp,
      hierarchy,
      responsive: "Stack mobile; 2 col tablet; 4 col desktop.",
      spacing: "gap spacing-6; section padding spacing-16+.",
      typography: "h2 section title; benefit titles h4; body bodySmall.",
      accessibility: "Ordered list semantics for benefits.",
      seoRelevance: "Keyword support from USP; H2 section heading.",
      interactionStates: "Static cards; optional secondary link hover.",
      animation: "Section reveal on scroll.",
      variants: "FeatureCard with icon; 3 or 4 columns based on USP length.",
      placeholders: "Icons from Lucide; no invented claims.",
      devNotes: `Split USP in content file; ${tokens}`,
    },
    TestimonialSection: {
      purpose: "Social proof for target audience.",
      content: "[PLACEHOLDER: quote, name, context] ×3",
      hierarchy,
      responsive: "Carousel mobile; 3-col grid desktop.",
      spacing: "Card padding spacing-6; carousel gap spacing-4.",
      typography: "Quote body; author caption.",
      accessibility: "blockquote + cite; carousel aria-live and controls.",
      seoRelevance: "Review schema only with real data [PLACEHOLDER].",
      interactionStates: "Carousel prev/next; pause on hover.",
      animation: "Slide 300ms between testimonials.",
      variants: "Carousel | grid.",
      placeholders: "No invented customer names or star counts.",
      devNotes: `TestimonialCard variant; ${tokens}`,
    },
    GalleryTeaser: {
      purpose: "Visual proof teaser linking to full gallery.",
      content: "4–6 thumbnails [PLACEHOLDER: gallery assets].",
      hierarchy,
      responsive: "2 col mobile; 4 col desktop.",
      spacing: "gap spacing-4; margin-top spacing-8 below heading.",
      typography: "h2 + optional bodySmall intro.",
      accessibility: "Alt text per thumbnail; link to gallery page.",
      seoRelevance: "Image alt supports image search intent.",
      interactionStates: "Thumbnail hover zoom; click to gallery page.",
      animation: "Lazy load blur-up.",
      variants: "Grid teaser; optional lightbox on teaser.",
      placeholders: "All gallery images [PLACEHOLDER].",
      devNotes: `Use MediaCard; link to ${ctx.pageLink("gallery")}; ${tokens}`,
    },
    LocationContactTeaser: {
      purpose: "Drive visit or contact with practical info.",
      content: ctx.brief.location
        ? `${ctx.brief.location}; hours [PLACEHOLDER]; contact [PLACEHOLDER]`
        : "[PLACEHOLDER: address, hours, contact]",
      hierarchy,
      responsive: "Stack mobile; split text/map desktop.",
      spacing: "padding spacing-8; gap spacing-6.",
      typography: "h2; body; link styles for contact.",
      accessibility: "tel:/mailto: labeled links.",
      seoRelevance: "Local NAP consistency.",
      interactionStates: "CTA buttons to contact/location pages.",
      animation: "Fade-in.",
      variants: "With/without mini-map thumbnail.",
      placeholders: "Phone, email, hours [PLACEHOLDER].",
      devNotes: `Link to ${ctx.pageLink("contact")} and ${ctx.pageLink("location")}; ${tokens}`,
    },
    FAQSection: {
      purpose: "Answer objections before final conversion.",
      content: "FAQ pairs from Page DNA section 3; brief-derived answers only.",
      hierarchy,
      responsive: "Full-width accordion all breakpoints.",
      spacing: "gap spacing-2 between items; section spacing-16.",
      typography: "h2 section; question label weight 600; answer body.",
      accessibility: "Accordion button aria-expanded; keyboard toggle.",
      seoRelevance: "FAQ structured data optional if Q&A confirmed.",
      interactionStates: "Expand/collapse; one or many open.",
      animation: "Height transition 200ms.",
      variants: "Single column accordion.",
      placeholders: "Answers requiring client data marked [PLACEHOLDER].",
      devNotes: `FAQAccordion from Design System; ${tokens}`,
    },
    FinalCTA: {
      purpose: "Exit conversion band before footer.",
      content: ctx.brief.website_goal,
      hierarchy,
      responsive: "Full-width buttons mobile; inline desktop.",
      spacing: "padding-y spacing-12; gap spacing-4 between CTAs.",
      typography: "h2 or bodyLarge + button token.",
      accessibility: "High contrast CTA pair; focus visible.",
      seoRelevance: "Supports conversion goal; no heading skip.",
      interactionStates: "Primary/secondary button full state machine.",
      animation: "Optional subtle entrance.",
      variants: "Centered band; split text+CTA.",
      placeholders: "None beyond goal copy from brief.",
      devNotes: `Reuse CTAButton primary+secondary; ${tokens}`,
    },
    MenuCategoryNav: {
      purpose: "Jump navigation across menu categories.",
      content:
        ctx.services.length > 0
          ? ctx.services.join(", ")
          : "[PLACEHOLDER: categories]",
      hierarchy,
      responsive: "Horizontal scroll pills mobile; sticky below hero optional.",
      spacing: "gap spacing-2; padding spacing-4.",
      typography: "label token on pills.",
      accessibility: "aria-current on active category; keyboard scroll.",
      seoRelevance: "Anchor links to category sections.",
      interactionStates: "Smooth scroll to anchors; active state on scroll spy optional.",
      animation: "None or subtle underline.",
      variants: "Pills | underline tabs.",
      placeholders: "Category names from brief services only.",
      devNotes: "Client component if scroll spy; anchor ids per category.",
    },
    MenuCategorySection: {
      purpose: "Display items for one menu category.",
      content: section?.contentRequirements ?? "[PLACEHOLDER: menu items with prices]",
      hierarchy,
      responsive: "1 col mobile; 2–3 col desktop cards.",
      spacing: "Section spacing-12 between categories; card gap spacing-4.",
      typography: "Category h2; item h4; description bodySmall; price label.",
      accessibility: "Price readable; dietary badges with text.",
      seoRelevance: "Menu/MenuItem schema [PLACEHOLDER: prices].",
      interactionStates: "Card hover; click to order/detail.",
      animation: "Stagger card reveal.",
      variants: "MenuItemCard; optional dietary badge.",
      placeholders: "Prices and descriptions [PLACEHOLDER].",
      devNotes: `Product/menu card variant; ${tokens}`,
    },
    DietaryAllergenNotes: {
      purpose: "Dietary compliance notes from brief USP.",
      content: ctx.brief.unique_selling_points ?? "[PLACEHOLDER: dietary notes]",
      hierarchy,
      responsive: "Full-width callout.",
      spacing: "padding spacing-4; margin spacing-8.",
      typography: "bodySmall in InfoCallout.",
      accessibility: "Info icon aria-label; not color-only.",
      seoRelevance: "Low; informational.",
      interactionStates: "Static.",
      animation: "None.",
      variants: "Info callout banner.",
      placeholders: "Allergen list [PLACEHOLDER: confirm with client].",
      devNotes: "Render only when brief USP mentions dietary keywords.",
    },
    MenuFilters: {
      purpose: "Filter menu grid when 3+ categories.",
      content: "Filter pills matching category names.",
      hierarchy,
      responsive: "Horizontal scroll on mobile.",
      spacing: "gap spacing-2; margin-bottom spacing-6.",
      typography: "label on pills.",
      accessibility: "aria-pressed on active filter.",
      seoRelevance: "None.",
      interactionStates: "Toggle filter; empty state when no matches.",
      animation: "Crossfade grid 200ms.",
      variants: "Omit when fewer than 3 categories.",
      placeholders: "N/A when omitted.",
      devNotes: "Connect to MenuEmptyState.",
    },
    MenuOrderCTA: {
      purpose: "Ordering conversion after menu browse.",
      content: ctx.brief.website_goal,
      hierarchy,
      responsive: "Sticky bottom bar mobile; inline section desktop.",
      spacing: "padding spacing-4 sticky bar; safe-area inset.",
      typography: "button token.",
      accessibility: "Sticky bar must not trap focus; z-index below modal.",
      seoRelevance: "Conversion path.",
      interactionStates: "Primary CTA loading if order URL async.",
      animation: "Slide-up sticky after hero scroll.",
      variants: "Sticky mobile | inline desktop.",
      placeholders: "Order URL [PLACEHOLDER: external system].",
      devNotes: `Label „${ctx.primaryCta}"; ${tokens}`,
    },
    MenuEmptyState: {
      purpose: "Zero-results UX for filters.",
      content: "No items match filter; reset or contact.",
      hierarchy,
      responsive: "Centered.",
      spacing: "padding spacing-12.",
      typography: "body + ghost button.",
      accessibility: "aria-live polite on filter change.",
      seoRelevance: "None.",
      interactionStates: "Reset filters button.",
      animation: "Fade-in message.",
      variants: "EmptyState standard.",
      placeholders: "N/A.",
      devNotes: "Show when client-side filter returns 0 items.",
    },
    BrandStory: {
      purpose: "Tell brand origin using brief facts only.",
      content: `${business} in ${ctx.brief.industry}; narrative [PLACEHOLDER].`,
      hierarchy,
      responsive: "Split text/image; stack mobile.",
      spacing: "gap spacing-8; section spacing-16.",
      typography: "h2; bodyLarge body paragraphs.",
      accessibility: "Logical reading order image after text on mobile.",
      seoRelevance: "About page E-E-A-T content.",
      interactionStates: "Static.",
      animation: "Optional image reveal.",
      variants: "StorySection two-column.",
      placeholders: "Story details [PLACEHOLDER: client narrative].",
      devNotes: `Content module fields; ${tokens}`,
    },
    MissionValues: {
      purpose: "Communicate mission aligned to website goal.",
      content: ctx.brief.website_goal,
      hierarchy,
      responsive: "3-col values grid desktop.",
      spacing: "gap spacing-6.",
      typography: "h2; value titles h4.",
      accessibility: "Ordered list of values.",
      seoRelevance: "Supporting about content.",
      interactionStates: "Static cards.",
      animation: "Stagger reveal.",
      variants: "ValuesGrid.",
      placeholders: "Value descriptions derived from USP only.",
      devNotes: tokens,
    },
    QualityPromise: {
      purpose: "Reinforce USP quality claim.",
      content: ctx.usp,
      hierarchy,
      responsive: "Centered narrow column.",
      spacing: "padding spacing-8.",
      typography: "blockquote or h2 + body.",
      accessibility: "blockquote cite to business name.",
      seoRelevance: "Trust content.",
      interactionStates: "Static.",
      animation: "Fade-in.",
      variants: "Blockquote emphasis.",
      placeholders: "No invented certifications.",
      devNotes: tokens,
    },
    TeamFounder: {
      purpose: "Humanize brand with team/founder placeholder.",
      content: "[PLACEHOLDER: name, role, bio, photo]",
      hierarchy,
      responsive: "1–3 card grid.",
      spacing: "gap spacing-6.",
      typography: "h3 name; caption role; bodySmall bio.",
      accessibility: "Photo alt includes name when known.",
      seoRelevance: "Person schema only with confirmed data.",
      interactionStates: "Optional link to team page.",
      animation: "Card hover subtle.",
      variants: "TeamMemberCard preview.",
      placeholders: "All team fields [PLACEHOLDER].",
      devNotes: "Do not invent names.",
    },
    TrustElements: {
      purpose: "Credibility badges from brief.",
      content: ctx.usp,
      hierarchy,
      responsive: "Horizontal scroll or grid.",
      spacing: "gap spacing-4.",
      typography: "label + bodySmall.",
      accessibility: "Text labels on all badges.",
      seoRelevance: "Trust signals.",
      interactionStates: "Static.",
      animation: "None.",
      variants: "TrustGrid.",
      placeholders: "Certification logos [PLACEHOLDER] if any.",
      devNotes: tokens,
    },
    GalleryFilterBar: {
      purpose: "Optional gallery category filters.",
      content: "[PLACEHOLDER: gallery categories]",
      hierarchy,
      responsive: "Horizontal scroll mobile.",
      spacing: "gap spacing-2; mb spacing-6.",
      typography: "label pills.",
      accessibility: "aria-pressed filters.",
      seoRelevance: "None.",
      interactionStates: "Filter toggles grid items.",
      animation: "Crossfade 250ms.",
      variants: "Omit if no categories confirmed.",
      placeholders: "Category names [PLACEHOLDER].",
      devNotes: "Client-side filter on grid.",
    },
    GalleryGrid: {
      purpose: "Display gallery images.",
      content: "6–12 images [PLACEHOLDER: assets].",
      hierarchy,
      responsive: "2 col mobile; 3–4 col desktop.",
      spacing: "gap spacing-4.",
      typography: "Optional caption caption token.",
      accessibility: "Keyboard navigable grid; alt required.",
      seoRelevance: "Image SEO via alt text.",
      interactionStates: "Click opens lightbox.",
      animation: "Lazy load skeleton until loaded.",
      variants: "Uniform grid; masonry optional.",
      placeholders: "All images [PLACEHOLDER].",
      devNotes: `GalleryGrid + LightboxDialog; ${tokens}`,
    },
    LightboxViewer: {
      purpose: "Fullscreen image viewing.",
      content: "Full-size image + caption [PLACEHOLDER].",
      hierarchy,
      responsive: "Fullscreen mobile; centered desktop max 90vw.",
      spacing: "padding spacing-4 controls.",
      typography: "caption for description.",
      accessibility: "Focus trap; Esc close; aria-modal; labeled nav buttons.",
      seoRelevance: "None.",
      interactionStates: "Open/close; prev/next.",
      animation: "Backdrop fade 200ms.",
      variants: "Dialog modal.",
      placeholders: "Captions [PLACEHOLDER].",
      devNotes: "Portal modal; restore focus on close.",
    },
    GalleryLoadingSkeleton: {
      purpose: "Loading placeholder for gallery grid.",
      content: "Skeleton cells matching grid count.",
      hierarchy,
      responsive: "Same grid as GalleryGrid.",
      spacing: "gap spacing-4.",
      typography: "N/A.",
      accessibility: "aria-busy on grid container until loaded.",
      seoRelevance: "None.",
      interactionStates: "Replace with images on load.",
      animation: "Pulse 1.5s.",
      variants: "SkeletonGrid.",
      placeholders: "N/A.",
      devNotes: "Remove skeleton when images onLoad complete.",
    },
    InstagramTeaser: {
      purpose: "Social gallery embed or link-out.",
      content: hasInstagram(ctx)
        ? "[PLACEHOLDER: Instagram handle/URL from client]"
        : "Omit section — not referenced in brief.",
      hierarchy,
      responsive: "2 col embed grid mobile.",
      spacing: "gap spacing-4.",
      typography: "h2 optional.",
      accessibility: "Mark external links.",
      seoRelevance: "None.",
      interactionStates: "External link or embed load.",
      animation: "Static embed.",
      variants: "Embed | link card | omitted.",
      placeholders: "Handle and feed content [PLACEHOLDER].",
      devNotes: "Do not invent Instagram account.",
    },
    GalleryFinalCTA: {
      purpose: "Convert after browsing gallery.",
      content: ctx.brief.website_goal,
      hierarchy,
      responsive: "Centered band.",
      spacing: "spacing-12 vertical.",
      typography: "h2 + button.",
      accessibility: "CTA contrast AA target.",
      seoRelevance: "Conversion.",
      interactionStates: "Primary CTA.",
      animation: "Fade-in.",
      variants: "FinalCTA narrow.",
      placeholders: "N/A.",
      devNotes: tokens,
    },
    ContactDetails: {
      purpose: "Direct contact channels.",
      content: "[PLACEHOLDER: phone, email, address]",
      hierarchy,
      responsive: "Stacked list mobile; 2 col desktop.",
      spacing: "gap spacing-4.",
      typography: "body with icons; links underline on hover.",
      accessibility: "tel:/mailto: accessible names.",
      seoRelevance: "ContactPage NAP.",
      interactionStates: "Click-to-call/email on mobile.",
      animation: "None.",
      variants: "ContactInfoList.",
      placeholders: "All contact fields [PLACEHOLDER] unless in brief.",
      devNotes: tokens,
    },
    ContactForm: {
      purpose: "Capture inquiries per brief goal.",
      content: "Fields: name, email, message required.",
      hierarchy,
      responsive: "max-w-lg centered; full width mobile.",
      spacing: "field gap spacing-4; label gap spacing-2.",
      typography: "label + body inputs; button token submit.",
      accessibility: "Labels, aria-describedby errors, aria-live submit.",
      seoRelevance: "Low.",
      interactionStates: "Validate on submit; loading spinner; success/error.",
      animation: "Error shake optional 100ms.",
      variants: "Standard 3-field form.",
      placeholders: "Privacy policy link [PLACEHOLDER].",
      devNotes: "Server action or API [PLACEHOLDER: endpoint].",
    },
    ContactFormValidation: {
      purpose: "Inline validation UX spec (logical part of ContactForm).",
      content: "Required, email format, inline errors.",
      hierarchy,
      responsive: "Errors below fields.",
      spacing: "error margin-top spacing-1.",
      typography: "bodySmall error color token.",
      accessibility: "aria-invalid; focus first error on submit.",
      seoRelevance: "None.",
      interactionStates: "Block submit until valid.",
      animation: "None.",
      variants: "Integrated into ContactForm.",
      placeholders: "N/A.",
      devNotes: "Implement inside ContactForm component.",
    },
    ContactFormSuccess: {
      purpose: "Post-submit confirmation.",
      content: "Thank you + [PLACEHOLDER: response time].",
      hierarchy,
      responsive: "Centered alert.",
      spacing: "padding spacing-6.",
      typography: "body success message.",
      accessibility: "role=status aria-live polite.",
      seoRelevance: "None.",
      interactionStates: "Replace form or show banner.",
      animation: "Checkmark draw optional.",
      variants: "SuccessAlert.",
      placeholders: "Response time [PLACEHOLDER].",
      devNotes: "Hide form on success or show inline.",
    },
    OpeningHours: {
      purpose: "Display operating hours.",
      content: "[PLACEHOLDER: Mo–Su hours]",
      hierarchy,
      responsive: "Full-width table.",
      spacing: "padding spacing-4.",
      typography: "bodySmall table cells.",
      accessibility: "table th scope attributes.",
      seoRelevance: "LocalBusiness hours schema when confirmed.",
      interactionStates: "Static.",
      animation: "None.",
      variants: "HoursTable.",
      placeholders: "All hours [PLACEHOLDER].",
      devNotes: "Shared on contact and location pages.",
    },
    MapEmbed: {
      purpose: "Show map for location/contact.",
      content: ctx.brief.location
        ? `Map for ${ctx.brief.location} [PLACEHOLDER: coordinates]`
        : "[PLACEHOLDER: map — no location in brief]",
      hierarchy,
      responsive: "16:9 embed; min-height 300px mobile.",
      spacing: "margin spacing-8.",
      typography: "iframe title descriptive.",
      accessibility: "Text address fallback below map.",
      seoRelevance: "Geo meta alignment.",
      interactionStates: "Lazy load on intersection.",
      animation: "Fade-in embed.",
      variants: "iframe | static image fallback.",
      placeholders: "Coordinates/ embed URL [PLACEHOLDER].",
      devNotes: "Defer third-party map script.",
    },
    DirectionsCTA: {
      purpose: "Open external maps for directions.",
      content: "[PLACEHOLDER: maps URL]",
      hierarchy,
      responsive: "Full-width button mobile.",
      spacing: "margin-top spacing-4.",
      typography: "button token.",
      accessibility: "Indicates opens external app.",
      seoRelevance: "Local intent helper.",
      interactionStates: "External link button hover.",
      animation: "None.",
      variants: "ExternalLinkButton.",
      placeholders: "Maps deep link [PLACEHOLDER].",
      devNotes: "target=_blank rel=noopener.",
    },
    AddressBlock: {
      purpose: "Structured address display.",
      content: ctx.brief.location
        ? `${ctx.brief.location} [PLACEHOLDER: street, PLZ, country]`
        : "[PLACEHOLDER: full address]",
      hierarchy,
      responsive: "Single column.",
      spacing: "padding spacing-4.",
      typography: "body; address element semantic.",
      accessibility: "Copy address button optional with feedback.",
      seoRelevance: "NAP / Local SEO critical.",
      interactionStates: "Copy to clipboard optional.",
      animation: "None.",
      variants: "AddressBlock.",
      placeholders: "Missing address parts [PLACEHOLDER].",
      devNotes: "Match footer NAP exactly.",
    },
    MapSection: {
      purpose: "Primary interactive map on location page.",
      content: "Same as MapEmbed with larger prominence.",
      hierarchy,
      responsive: "min-height 450px desktop.",
      spacing: "section spacing-12.",
      typography: "h2 optional above map.",
      accessibility: "Address fallback required.",
      seoRelevance: "LocalBusiness geo.",
      interactionStates: "Pin click → directions.",
      animation: "Lazy load.",
      variants: "Full-width map section.",
      placeholders: "Lat/lng [PLACEHOLDER].",
      devNotes: "Reuse MapEmbed with size variant.",
    },
    DirectionsGuide: {
      purpose: "Text directions for visitors.",
      content: "[PLACEHOLDER: driving/transit directions]",
      hierarchy,
      responsive: "Accordion stacked mobile.",
      spacing: "gap spacing-2.",
      typography: "h3 accordion triggers; body steps.",
      accessibility: "Accordion keyboard support.",
      seoRelevance: "Local content.",
      interactionStates: "Expand/collapse sections.",
      animation: "Accordion 200ms.",
      variants: "DirectionsAccordion.",
      placeholders: "Do not invent landmarks.",
      devNotes: tokens,
    },
    ParkingTransit: {
      purpose: "Parking and transit guidance.",
      content: "[PLACEHOLDER: parking and transit info]",
      hierarchy,
      responsive: "2 col info grid tablet+.",
      spacing: "gap spacing-6.",
      typography: "h4 labels; bodySmall details.",
      accessibility: "Icons with text labels.",
      seoRelevance: "Local helper content.",
      interactionStates: "Static.",
      animation: "None.",
      variants: "InfoGrid.",
      placeholders: "All transit/parking facts [PLACEHOLDER].",
      devNotes: tokens,
    },
    LocalSEOBlock: {
      purpose: "Visible NAP for local SEO consistency.",
      content: `${business}${ctx.brief.location ? `, ${ctx.brief.location}` : ""} [PLACEHOLDER: phone]`,
      hierarchy,
      responsive: "Footer-adjacent block.",
      spacing: "padding spacing-6.",
      typography: "bodySmall NAP lines.",
      accessibility: "Structured visible text matching schema.",
      seoRelevance: "Critical — matches JSON-LD LocalBusiness.",
      interactionStates: "Static.",
      animation: "None.",
      variants: "LocalBusinessSnippet.",
      placeholders: "Phone [PLACEHOLDER].",
      devNotes: "Sync with structured data on page.",
    },
    NearbyLandmarks: {
      purpose: "Orientation landmarks when client confirms.",
      content: "[PLACEHOLDER: nearby landmarks list]",
      hierarchy,
      responsive: "Single column list.",
      spacing: "gap spacing-2.",
      typography: "bodySmall list items.",
      accessibility: "ul semantic list.",
      seoRelevance: "Minor local context.",
      interactionStates: "Static.",
      animation: "None.",
      variants: "LandmarkList.",
      placeholders: "Do not invent landmark names.",
      devNotes: "Omit list items until client provides.",
    },
    NavigateCTA: {
      purpose: "Mobile navigate action.",
      content: "[PLACEHOLDER: maps deep link]",
      hierarchy,
      responsive: "Sticky bottom mobile only.",
      spacing: "safe-area padding spacing-4.",
      typography: "button token full width.",
      accessibility: "44px height; external indication.",
      seoRelevance: "Local conversion.",
      interactionStates: "Sticky after map in viewport.",
      animation: "Slide-up bar.",
      variants: "Sticky mobile CTA.",
      placeholders: "Maps URL [PLACEHOLDER].",
      devNotes: "Hide on desktop if inline directions sufficient.",
    },
    PortfolioGrid: {
      purpose: "Showcase portfolio projects.",
      content: "[PLACEHOLDER: project cases]",
      hierarchy,
      responsive: "1–3 col responsive grid.",
      spacing: "gap spacing-6.",
      typography: "h3 project title; caption tags.",
      accessibility: "Filter buttons accessible.",
      seoRelevance: "Portfolio content keywords.",
      interactionStates: "Filter + card hover overlay.",
      animation: "Reveal on scroll.",
      variants: "ProjectCard + FilterBar.",
      placeholders: "No invented client names.",
      devNotes: tokens,
    },
    ReviewsSummary: {
      purpose: "Aggregate reviews display.",
      content: "[PLACEHOLDER: average rating, count, quotes]",
      hierarchy,
      responsive: "Grid of review cards.",
      spacing: "gap spacing-6.",
      typography: "Rating text alternative to stars.",
      accessibility: "Do not rely on color alone for stars.",
      seoRelevance: "Review schema only with real ratings.",
      interactionStates: "Carousel optional.",
      animation: "Carousel slide.",
      variants: "ReviewCard grid.",
      placeholders: "No invented star counts.",
      devNotes: tokens,
    },
    TeamGrid: {
      purpose: "Team member profiles.",
      content: "[PLACEHOLDER: members]",
      hierarchy,
      responsive: "1 col mobile; 3 col desktop.",
      spacing: "gap spacing-6.",
      typography: "h3 name; caption role.",
      accessibility: "Photo alt with name.",
      seoRelevance: "Person schema when confirmed.",
      interactionStates: "Card hover.",
      animation: "Subtle scale hover.",
      variants: "TeamMemberCard.",
      placeholders: "Names/photos [PLACEHOLDER].",
      devNotes: "Do not invent people.",
    },
    TreatmentList: {
      purpose: "List treatment categories.",
      content: "[PLACEHOLDER: treatments]",
      hierarchy,
      responsive: "Stacked cards.",
      spacing: "gap spacing-6.",
      typography: "h2 categories; body descriptions.",
      accessibility: "Clear headings per treatment.",
      seoRelevance: "Medical/service keywords [PLACEHOLDER].",
      interactionStates: "CTA per card to contact.",
      animation: "Scroll reveal.",
      variants: "TreatmentCard list.",
      placeholders: "Treatment details [PLACEHOLDER].",
      devNotes: "Calm clinical tone; no medical guarantees.",
    },
    ServiceCard: {
      purpose: "Describe one service offering.",
      content: section?.contentRequirements ?? "[PLACEHOLDER: service details]",
      hierarchy,
      responsive: "Alternating sections optional.",
      spacing: "section spacing-12.",
      typography: "h2 service name; body copy.",
      accessibility: "Heading per service block.",
      seoRelevance: "Service keywords from brief.",
      interactionStates: "CTA to contact.",
      animation: "Reveal on scroll.",
      variants: "ServiceCard + FAQ optional.",
      placeholders: "Pricing/process [PLACEHOLDER].",
      devNotes: tokens,
    },
    ContentBlocks: {
      purpose: "Flexible content sections for generic pages.",
      content: "[PLACEHOLDER: page content from brief expansion]",
      hierarchy,
      responsive: "Configurable grid.",
      spacing: "spacing-8 between blocks.",
      typography: "h2/h3 per block.",
      accessibility: "Maintain heading order.",
      seoRelevance: "Page-specific keywords.",
      interactionStates: "Inline CTAs optional.",
      animation: "Section reveal.",
      variants: "RichText + media blocks.",
      placeholders: "Content [PLACEHOLDER].",
      devNotes: tokens,
    },
  };

  const template = templates[normalized] ?? {
    purpose: section?.purpose ?? `Render ${name} section on ${ctx.page}.`,
    content: section?.contentRequirements ?? "[PLACEHOLDER: content]",
    hierarchy,
    responsive: section?.responsive ?? "Follow Page DNA responsive spec.",
    spacing: "Section spacing per Design System DNA spacing tokens.",
    typography: "Section heading h2; body body token.",
    accessibility: section?.accessibility ?? "Follow WCAG AA patterns.",
    seoRelevance: "Align with page SEO spec in Page DNA section 7.",
    interactionStates: section?.ctaBehavior ?? "Follow Page DNA section 6.",
    animation: section?.motion ?? baseMotion(ctx),
    variants: `Default ${normalized} layout.`,
    placeholders: "Mark missing copy/images [PLACEHOLDER].",
    devNotes: `Implement as reusable ${normalized} component; ${tokens}`,
  };

  return {
    ...template,
    hierarchy,
    content: section?.contentRequirements && normalized !== "SiteHeader" && normalized !== "SiteFooter"
      ? `${template.content} | Section: ${section.contentRequirements.slice(0, 80)}`
      : template.content,
  };
}

function hasInstagram(ctx: PageDnaContext): boolean {
  return /instagram|insta|social/i.test(
    `${ctx.brief.reference_websites ?? ""} ${ctx.brief.required_features ?? ""} ${ctx.brief.additional_notes ?? ""}`,
  );
}

export function buildPageComponentDna(ctx: PageDnaContext): string[] {
  const tree = getComponentTreeNodes(ctx.role, ctx);
  const lines: string[] = [
    "## 9. Component DNA",
    "Reusable UI components for this page — reference Design System DNA tokens for all styling.",
    "",
  ];

  tree.forEach((componentName, index) => {
    const fields = buildComponentFields(componentName, ctx, index, tree);
    lines.push(formatComponentDna(componentName, fields));
  });

  return lines;
}

export function buildSiteComponentCatalog(
  pages: Array<{ page: string; role: PageRole; ctx: PageDnaContext }>,
): string[] {
  const unique = new Set<string>();
  for (const entry of pages) {
    getComponentTreeNodes(entry.role, entry.ctx).forEach((name) =>
      unique.add(normalizeComponentName(name)),
    );
  }

  return [
    "# Component DNA — Site-wide reusable catalog",
    `Unique component types (${unique.size}): ${[...unique].sort().join(", ")}.`,
    "Implement each type once in components/ and compose pages from props/content modules.",
    "Per-page Component DNA in recommendedPageSections defines page-specific content and hierarchy.",
  ];
}

export function extractComponentDnaWordCount(pageSpecs: string[]): number {
  return pageSpecs
    .filter((line) => line.startsWith("Component:"))
    .join(" ")
    .split(/\s+/)
    .filter(Boolean).length;
}
