import type { GeneratedNextJsProject } from "@/lib/project-generator/types";
import { buildVirtualFile } from "@/lib/project-generator/tree";
import type { VirtualFile } from "@/lib/project-generator/types";
import { ASSET_DEFINITIONS } from "@/lib/project-generator/asset-utils";
import { findDuplicateExports } from "@/lib/project-generator/react-component-registry";
import { countClientComponents, countVisualComponentFiles } from "@/lib/project-generator/visual-components";
import { findUnresolvedImports } from "@/lib/project-generator/react-pages.verify";
import { verifyStyleEngineFiles } from "@/lib/project-generator/style-engine.verify";
import { computeTreeChecksum } from "@/lib/project-export/checksum";
import { buildExportManifest, serializeExportManifest } from "@/lib/project-export/manifest";
import {
  REQUIRED_ROOT_FILES,
  classifyPlaceholderCategory,
  detectAbsoluteLocalPaths,
  detectSecrets,
  extractMetadataField,
  mergeVirtualFiles,
  normalizeExportDirectories,
  normalizeExportFiles,
  normalizeLineEndings,
} from "@/lib/project-export/normalize";
import type {
  ExportableWebsiteProject,
  ExportDependencySummary,
  ExportPlaceholderEntry,
  ExportProjectMetadata,
  ExportRouteSummary,
  ExportValidationSummary,
  ExportWarning,
  NormalizedExportFile,
  PlaceholderCategory,
  ZipReadyEntry,
} from "@/lib/project-export/types";
import {
  EXPORT_MANIFEST_PATH,
  EXPORT_PLACEHOLDER_REPORT_PATH,
  EXPORT_VERSION,
} from "@/lib/project-export/types";

const ALLOWED_DEPENDENCIES = ["next", "react", "react-dom"] as const;
const ALLOWED_DEV_DEPENDENCIES = [
  "@tailwindcss/postcss",
  "@types/node",
  "@types/react",
  "@types/react-dom",
  "eslint",
  "eslint-config-next",
  "tailwindcss",
  "typescript",
] as const;
const REQUIRED_SCRIPTS = ["dev", "build", "start", "lint"] as const;

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function extractProjectMetadata(generated: GeneratedNextJsProject): ExportProjectMetadata {
  const siteConfig = generated.files.find((file) => file.path === "lib/site-config.ts")?.content ?? "";

  return {
    projectId: generated.sourceProjectId,
    projectName: generated.sourceProjectName,
    compilerVersion: extractMetadataField(siteConfig, "compilerVersion"),
    generatorVersion: generated.generatorVersion,
    sourceBlueprintId: extractMetadataField(siteConfig, "sourceBlueprintId"),
    sourceBriefId: extractMetadataField(siteConfig, "sourceBriefId"),
    targetFramework: generated.targetFramework,
  };
}

export function buildExportGitignore(): string {
  return normalizeLineEndings(
    [
      "# Generated by AIOS Project Export Engine",
      "",
      "node_modules/",
      ".next/",
      "out/",
      "dist/",
      "build/",
      "coverage/",
      "",
      ".env.local",
      ".env.*.local",
      ".env",
      "",
      "npm-debug.log*",
      "yarn-debug.log*",
      "yarn-error.log*",
      "pnpm-debug.log*",
      "",
      ".DS_Store",
      "Thumbs.db",
      "",
      "*.swp",
      "*.swo",
      ".idea/",
      ".vscode/",
      "",
      "next-env.d.ts",
      "",
    ].join("\n"),
  );
}

export function buildExportEnvExample(projectName: string): string {
  return normalizeLineEndings(
    [
      "# Generated environment example — replace values before production",
      `# Project: ${projectName}`,
      "",
      "# Public site URL (optional for local development)",
      "NEXT_PUBLIC_SITE_URL=",
      "",
      "# No secrets are required for the current frontend-only export.",
      "",
    ].join("\n"),
  );
}

export function buildExportReadme(
  generated: GeneratedNextJsProject,
  metadata: ExportProjectMetadata,
  routes: ExportRouteSummary[],
  placeholderCount: number,
): string {
  return normalizeLineEndings(
    [
      `# ${metadata.projectName}`,
      "",
      "Deterministic Next.js App Router website export generated by AIOS.",
      "",
      "## Technology stack",
      "",
      "- Next.js App Router",
      "- React",
      "- TypeScript",
      "- Tailwind CSS v4",
      "- Generated design token system",
      "",
      "## Prerequisites",
      "",
      "- Node.js 20+",
      "- npm",
      "",
      "## Installation",
      "",
      "```bash",
      "npm install",
      "```",
      "",
      "## Development",
      "",
      "```bash",
      "npm run dev",
      "```",
      "",
      "## Build",
      "",
      "```bash",
      "npm run build",
      "```",
      "",
      "## Start",
      "",
      "```bash",
      "npm run start",
      "```",
      "",
      "## Folder overview",
      "",
      "- `app/` — App Router pages and layouts",
      "- `components/generated/` — generated visual components",
      "- `content/` — structured page content",
      "- `lib/assets/` — asset registry and `resolveAsset()` helper",
      "- `public/` — placeholder SVG assets",
      "- `styles/` — design tokens and global styles",
      "- `types/` — generated metadata types",
      "",
      "## Content editing",
      "",
      "- Update page content under `content/pages/` and generated page configs.",
      "- Do not invent business facts; replace placeholders with confirmed content only.",
      "",
      "## Asset replacement",
      "",
      "- Request assets through `resolveAsset()` only.",
      "- Replace placeholder SVG files under `public/icons/` and `public/images/`.",
      "- Keep asset registry entries aligned with exported files.",
      "",
      "## Placeholder checklist",
      "",
      `- ${placeholderCount} placeholders detected in this export.`,
      "- Review `export-placeholder-report.json` before launch.",
      "- Replace launch-blocking placeholders first.",
      "",
      "## Environment variables",
      "",
      "- Copy `.env.example` to `.env.local` for local overrides.",
      "- Never commit real secrets.",
      "",
      "## Deployment notes",
      "",
      "- Replace all placeholders before production.",
      "- Verify build locally with `npm run build`.",
      "- Deployment target is project-specific and not included in this export.",
      "",
      "## Accessibility notes",
      "",
      "- Components include semantic landmarks, skip links, and focus-visible treatments.",
      "- Replace placeholder alt text with confirmed descriptions.",
      "",
      "## Routes",
      "",
      ...routes.map((route) => `- \`${route.routePath}\` → \`${route.pageFilePath}\``),
      "",
      "## Export metadata",
      "",
      `- Export version: ${EXPORT_VERSION}`,
      `- Generator version: ${metadata.generatorVersion}`,
      `- Compiler version: ${metadata.compilerVersion}`,
      `- Generated at: ${generated.generatedAt}`,
      "",
    ].join("\n"),
  );
}

function buildPlaceholderReport(
  generated: GeneratedNextJsProject,
  normalizedFiles: NormalizedExportFile[],
): ExportPlaceholderEntry[] {
  const entries: ExportPlaceholderEntry[] = [];
  let counter = 0;

  for (const file of normalizedFiles) {
    const matches = file.content.match(/\[PLACEHOLDER:[^\]]+\]/g) ?? [];
    for (const match of matches) {
      counter += 1;
      const category = classifyPlaceholderCategory(match);
      entries.push({
        id: `placeholder-${counter}`,
        category,
        filePath: file.path,
        affectedRoute: inferRouteForFile(generated, file.path),
        affectedComponent: inferComponentForFile(file.path),
        severity: category === "legal" || category === "testimonial" ? "warning" : "info",
        blocksLaunch: category === "legal" || category === "testimonial" || category === "domain",
        replacementInstruction: `Replace ${match} with confirmed ${category} content.`,
      });
    }

    const categoryMatches = file.content.matchAll(/category="([^"]+)"/g);
    for (const match of categoryMatches) {
      counter += 1;
      const category = classifyPlaceholderCategory(match[1]);
      entries.push({
        id: `placeholder-${counter}`,
        category,
        filePath: file.path,
        affectedRoute: inferRouteForFile(generated, file.path),
        affectedComponent: inferComponentForFile(file.path),
        severity: "info",
        blocksLaunch: match[1] === "legal",
        replacementInstruction: `Replace ${match[1]} placeholder in ${file.path}.`,
      });
    }
  }

  return entries.sort((left, right) => left.id.localeCompare(right.id));
}

function inferRouteForFile(generated: GeneratedNextJsProject, filePath: string): string | null {
  const route = generated.routes.find((entry) => entry.pageFilePath === filePath);
  return route?.routePath ?? null;
}

function inferComponentForFile(filePath: string): string | null {
  if (filePath.startsWith("components/generated/") && filePath.endsWith(".tsx")) {
    return filePath.replace("components/generated/", "").replace(".tsx", "");
  }
  return null;
}

function validateDependencies(files: VirtualFile[]): ExportDependencySummary {
  const packageFile = files.find((file) => file.path === "package.json");
  const issues: string[] = [];

  if (!packageFile) {
    return {
      packageName: "unknown",
      dependencyCount: 0,
      devDependencyCount: 0,
      scripts: [],
      valid: false,
      issues: ["Missing package.json"],
    };
  }

  const parsed = JSON.parse(packageFile.content) as {
    name?: string;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    scripts?: Record<string, string>;
  };

  const dependencies = Object.keys(parsed.dependencies ?? {});
  const devDependencies = Object.keys(parsed.devDependencies ?? {});
  const scripts = Object.keys(parsed.scripts ?? {});

  for (const dep of dependencies) {
    if (!(ALLOWED_DEPENDENCIES as readonly string[]).includes(dep)) {
      issues.push(`Unsupported dependency: ${dep}`);
    }
  }

  for (const dep of devDependencies) {
    if (!(ALLOWED_DEV_DEPENDENCIES as readonly string[]).includes(dep)) {
      issues.push(`Unsupported devDependency: ${dep}`);
    }
  }

  for (const script of REQUIRED_SCRIPTS) {
    if (!scripts.includes(script)) {
      issues.push(`Missing script: ${script}`);
    }
  }

  if (new Set(dependencies).size !== dependencies.length) {
    issues.push("Duplicate dependencies detected");
  }
  if (new Set(devDependencies).size !== devDependencies.length) {
    issues.push("Duplicate devDependencies detected");
  }

  return {
    packageName: parsed.name ?? "generated-website",
    dependencyCount: dependencies.length,
    devDependencyCount: devDependencies.length,
    scripts,
    valid: issues.length === 0,
    issues,
  };
}

function countUnknownTokens(files: VirtualFile[]): number {
  const cssVariablesFile = files.find((file) => file.path === "styles/css-variables.ts");
  const knownVariables = new Set(
    cssVariablesFile
      ? [...cssVariablesFile.content.matchAll(/"(--[^"]+)"/g)].map((match) => match[1])
      : [],
  );
  knownVariables.add("--color-error");

  let unknown = 0;
  for (const file of files.filter((item) => item.path.startsWith("components/generated/"))) {
    for (const match of file.content.matchAll(/var\((--[^)]+)\)/g)) {
      if (!knownVariables.has(match[1])) {
        unknown += 1;
      }
    }
  }
  return unknown;
}

function validateAssets(files: VirtualFile[]): { valid: boolean; unresolved: number } {
  let unresolved = 0;

  for (const asset of ASSET_DEFINITIONS) {
    const virtualPath =
      asset.id === "logo" || asset.id === "favicon"
        ? `public/icons/${asset.fileName}`
        : `public/images/${asset.fileName}`;

    const assetFile = files.find((file) => file.path === virtualPath);
    if (!assetFile) {
      unresolved += 1;
      continue;
    }

    if (!assetFile.content.includes("ASSET_METADATA:")) {
      unresolved += 1;
    }
  }

  const directImagePaths = files
    .filter((file) => file.path.startsWith("components/generated/"))
    .reduce((count, file) => {
      return (
        count +
        (file.content.match(/src="\/(?:images|icons)\//g)?.length ?? 0) +
        (file.content.match(/src='\/(?:images|icons)\//g)?.length ?? 0)
      );
    }, 0);

  return {
    valid: unresolved === 0 && directImagePaths === 0,
    unresolved: unresolved + directImagePaths,
  };
}

function buildValidationSummary(
  generated: GeneratedNextJsProject,
  normalizedFiles: NormalizedExportFile[],
  virtualFiles: VirtualFile[],
  dependencySummary: ExportDependencySummary,
): ExportValidationSummary {
  const paths = normalizedFiles.map((file) => file.path);
  const duplicatePathCount = paths.length - new Set(paths).size;
  const directoryPaths = normalizeExportDirectories(normalizedFiles).map((dir) => dir.path);
  const unresolvedImports = findUnresolvedImports(virtualFiles);
  const assetValidation = validateAssets(virtualFiles);
  const styleValidation = verifyStyleEngineFiles({
    ...generated,
    files: virtualFiles,
  });
  const registry = virtualFiles.find((file) => file.path === "components/generated/index.ts");
  const duplicateExports = registry ? findDuplicateExports(registry.content) : [];
  const secretCount = virtualFiles.reduce(
    (count, file) => count + detectSecrets(file.path, file.content),
    0,
  );
  const absolutePathCount = virtualFiles.reduce(
    (count, file) => count + detectAbsoluteLocalPaths(file.content),
    0,
  );
  const unknownTokenCount = countUnknownTokens(virtualFiles);
  const requiredRootFilesPresent = REQUIRED_ROOT_FILES.every((path) => paths.includes(path));
  const routesValid =
    generated.routes.some((route) => route.routePath === "/") &&
    generated.routes.every((route) => virtualFiles.some((file) => file.path === route.pageFilePath)) &&
    virtualFiles.some((file) => file.path === "app/layout.tsx") &&
    virtualFiles.some((file) => file.path === "app/not-found.tsx");

  const emptyRequiredFiles = normalizedFiles.filter((file) => file.required && file.byteLength === 0);

  return {
    passed:
      duplicatePathCount === 0 &&
      duplicateExports.length === 0 &&
      unresolvedImports.length === 0 &&
      assetValidation.valid &&
      styleValidation.passed &&
      dependencySummary.valid &&
      requiredRootFilesPresent &&
      emptyRequiredFiles.length === 0 &&
      routesValid &&
      secretCount === 0 &&
      absolutePathCount === 0 &&
      !virtualFiles.some((file) => file.path === ".env.local"),
    uniqueFilePaths: duplicatePathCount === 0,
    uniqueDirectoryPaths: directoryPaths.length === new Set(directoryPaths).size,
    requiredRootFilesPresent,
    routesValid,
    componentsValid: unresolvedImports.length === 0 && duplicateExports.length === 0,
    assetsValid: assetValidation.valid,
    stylingValid: styleValidation.passed,
    dependenciesValid: dependencySummary.valid,
    securityValid: secretCount === 0 && absolutePathCount === 0,
    unresolvedImportCount: unresolvedImports.length,
    unresolvedAssetCount: assetValidation.unresolved,
    unknownTokenCount,
    detectedSecretCount: secretCount,
    absoluteLocalPathCount: absolutePathCount,
    duplicatePathCount,
  };
}

function buildWarnings(validation: ExportValidationSummary): ExportWarning[] {
  const warnings: ExportWarning[] = [];

  if (!validation.dependenciesValid) {
    warnings.push({
      code: "DEPENDENCY_VALIDATION",
      severity: "warning",
      message: "Dependency validation reported issues",
      filePath: "package.json",
    });
  }

  if (validation.unresolvedImportCount > 0) {
    warnings.push({
      code: "UNRESOLVED_IMPORTS",
      severity: "error",
      message: `${validation.unresolvedImportCount} unresolved imports`,
      filePath: null,
    });
  }

  if (validation.unresolvedAssetCount > 0) {
    warnings.push({
      code: "UNRESOLVED_ASSETS",
      severity: "error",
      message: `${validation.unresolvedAssetCount} unresolved assets`,
      filePath: null,
    });
  }

  return warnings.sort((left, right) => left.code.localeCompare(right.code));
}

function buildZipReadyEntries(files: NormalizedExportFile[]): ZipReadyEntry[] {
  return files.map((file) => ({
    relativePath: file.path,
    content: file.content,
    encoding: file.encoding,
    byteLength: file.byteLength,
    checksum: file.checksum,
  }));
}

function buildOverlayFiles(
  generated: GeneratedNextJsProject,
  metadata: ExportProjectMetadata,
  routes: ExportRouteSummary[],
  placeholderCount: number,
): VirtualFile[] {
  return [
    buildVirtualFile(".gitignore", "config", buildExportGitignore(), {
      description: "Export gitignore",
      implementationStatus: "generated",
    }),
    buildVirtualFile(".env.example", "config", buildExportEnvExample(metadata.projectName), {
      description: "Export environment example",
      implementationStatus: "generated",
    }),
    buildVirtualFile(
      "README.md",
      "documentation",
      buildExportReadme(generated, metadata, routes, placeholderCount),
      {
        description: "Export README",
        implementationStatus: "generated",
      },
    ),
  ];
}

export function buildExportableWebsiteProject(
  generated: GeneratedNextJsProject,
): ExportableWebsiteProject {
  const metadata = extractProjectMetadata(generated);
  const routeSummary: ExportRouteSummary[] = generated.routes
    .map((route) => ({
      id: route.id,
      routePath: route.routePath,
      pageFilePath: route.pageFilePath,
      pageRole: route.pageRole,
      seoTitle: route.seoTitle,
    }))
    .sort((left, right) => left.routePath.localeCompare(right.routePath));

  const preliminaryNormalized = normalizeExportFiles(generated.files);
  const preliminaryPlaceholderReport = buildPlaceholderReport(generated, preliminaryNormalized);
  const overlay = buildOverlayFiles(
    generated,
    metadata,
    routeSummary,
    preliminaryPlaceholderReport.length,
  );
  const mergedVirtualFiles = mergeVirtualFiles(generated.files, overlay);
  const normalizedFiles = normalizeExportFiles(mergedVirtualFiles);
  const placeholderReport = buildPlaceholderReport(generated, normalizedFiles);
  const directories = normalizeExportDirectories(normalizedFiles);
  const treeChecksum = computeTreeChecksum(normalizedFiles);
  const dependencySummary = validateDependencies(mergedVirtualFiles);
  const validationSummary = buildValidationSummary(
    generated,
    normalizedFiles,
    mergedVirtualFiles,
    dependencySummary,
  );
  const warnings = buildWarnings(validationSummary);

  const manifest = buildExportManifest({
    metadata,
    generatedAt: generated.generatedAt,
    files: normalizedFiles,
    directoryCount: directories.length,
    routeCount: generated.routes.length,
    componentCount: countVisualComponentFiles(mergedVirtualFiles),
    assetCount: ASSET_DEFINITIONS.length,
    checksum: treeChecksum,
    placeholderReport,
    warnings,
    missingDataCount: placeholderReport.filter((entry) => entry.blocksLaunch).length,
  });

  const manifestFile = buildVirtualFile(
    EXPORT_MANIFEST_PATH,
    "documentation",
    serializeExportManifest(manifest),
    {
      description: "Export manifest",
      implementationStatus: "generated",
    },
  );

  const placeholderReportFile = buildVirtualFile(
    EXPORT_PLACEHOLDER_REPORT_PATH,
    "documentation",
    json(placeholderReport),
    {
      description: "Centralized placeholder report",
      implementationStatus: "generated",
    },
  );

  const virtualFiles = mergeVirtualFiles(mergedVirtualFiles, [manifestFile, placeholderReportFile]);
  const finalNormalizedFiles = normalizeExportFiles(virtualFiles);
  const finalChecksum = computeTreeChecksum(finalNormalizedFiles);

  return {
    exportVersion: EXPORT_VERSION,
    generatedAt: generated.generatedAt,
    checksum: finalChecksum,
    projectMetadata: metadata,
    manifest: {
      ...manifest,
      checksum: finalChecksum,
      fileCount: finalNormalizedFiles.length,
    },
    files: finalNormalizedFiles,
    directories: normalizeExportDirectories(finalNormalizedFiles),
    virtualFiles,
    zipReadyEntries: buildZipReadyEntries(finalNormalizedFiles),
    routeSummary,
    componentSummary: {
      registryPath: "components/generated/index.ts",
      exportCount: countVisualComponentFiles(mergedVirtualFiles),
      descriptorCount: generated.componentDescriptors.length,
      clientComponentCount: countClientComponents(mergedVirtualFiles),
      serverComponentCount:
        countVisualComponentFiles(mergedVirtualFiles) - countClientComponents(mergedVirtualFiles),
    },
    assetSummary: {
      registryPath: "lib/assets/registry.ts",
      assetCount: ASSET_DEFINITIONS.length,
      placeholderAssetCount: ASSET_DEFINITIONS.length,
      resolvedAssetCount: ASSET_DEFINITIONS.length,
    },
    dependencySummary,
    validationSummary,
    placeholderReport,
    warnings,
    routes: generated.routes,
    componentDescriptors: generated.componentDescriptors,
  };
}

export function serializeExportPackageJson(exportPackage: ExportableWebsiteProject): string {
  return json({
    exportVersion: exportPackage.exportVersion,
    generatedAt: exportPackage.generatedAt,
    checksum: exportPackage.checksum,
    manifest: exportPackage.manifest,
    files: exportPackage.files.map((file) => ({
      path: file.path,
      checksum: file.checksum,
      byteLength: file.byteLength,
    })),
    directories: exportPackage.directories.map((directory) => directory.path),
    validationSummary: exportPackage.validationSummary,
  });
}

export function serializeManifestJson(exportPackage: ExportableWebsiteProject): string {
  return serializeExportManifest(exportPackage.manifest);
}

export function serializePlaceholderReportJson(exportPackage: ExportableWebsiteProject): string {
  return json(exportPackage.placeholderReport);
}

export function serializeChecksumReport(exportPackage: ExportableWebsiteProject): string {
  return json({
    algorithm: exportPackage.manifest.checksumAlgorithm,
    projectChecksum: exportPackage.checksum,
    fileChecksums: exportPackage.files.map((file) => ({
      path: file.path,
      checksum: file.checksum,
    })),
  });
}

export function countPlaceholdersByCategory(
  report: ExportPlaceholderEntry[],
): Record<PlaceholderCategory, number> {
  const categories: Record<PlaceholderCategory, number> = {
    logo: 0,
    image: 0,
    price: 0,
    address: 0,
    phone: 0,
    email: 0,
    "opening-hours": 0,
    testimonial: 0,
    legal: 0,
    map: 0,
    "social-link": 0,
    "product-data": 0,
    domain: 0,
    other: 0,
  };

  for (const entry of report) {
    categories[entry.category] += 1;
  }

  return categories;
}
